# https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml
[versions]
detekt = "1.23.6"
gradle = "8.7"
#gradle-plugin-publish = ""
kotlin = "1.9.22"
junit = "5.8.2"
spek = "1.2.1"

[libraries]
#versions = { id = "com.github.ben-manes.versions", version = "0.45.0" }

#[bundles]
#groovy = ["groovy-core", "groovy-json", "groovy-nio"]

[plugins]
#detekt = { module = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#publish = { module = "com.gradle.plugin-publish", version = "0.10.1" }
